/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            'code::before': {
              content: '&nbsp;&nbsp;',
            },
            'code::after': {
              content: '&nbsp;&nbsp;',
            },
            code: {
              wordWrap: 'break-word',
              boxDecorationBreak: 'clone',
              padding: '.1rem .3rem .2rem',
              borderRadius: '.2rem',
            }
          },
        },
      }
    },
    animation: {
      'congrats': 'wiggle 0.3s linear infinite',
      'leftToRight':'leftToRight 15s ease infinite',
      textLeft: 'pulses 2s',
      textRight: 'pulses 3s',
    },
    keyframes: {
      pulses: {
        "0%": { opacity: "0" },
        "75%": { opacity: "0" },
        "100%": { opacity: "1" },
      },
      wiggle: {
        '0%': { transform: 'translate(1px, 1px) rotate(0deg)' },
        '10%': { transform: 'translate(-1px, -2px) rotate(-1deg)' },
        '20%': { transform: 'translate(-3px, 0px) rotate(1deg)' },
        '30%': { transform: 'translate(3px, 2px) rotate(0deg)' },
        '40%': { transform: 'translate(1px, -1px) rotate(1deg)' },
        '50%': { transform: 'translate(-1px, 2px) rotate(-1deg)' },
        '60%': { transform: 'translate(-3px, 1px) rotate(0deg)' },
        '70%': { transform: 'translate(3px, 1px) rotate(-1deg)' },
        '80%': { transform: 'translate(-1px, -1px) rotate(1deg)' },
        '90%': { transform: 'translate(1px, 2px) rotate(0deg)' },
        '100%': { transform: 'translate(1px, -2px) rotate(-1deg)' },
      },
      leftToRight: {
        '0%': {
            'background-size':'400% 400%',
            'background-position': '0% 50%'
        },
        '50%': {
            'background-size':'400% 400%',
            'background-position': '100% 50%'
        },
        '100%': {
          'background-size':'400% 400%',
          'background-position': '0% 50%'
      },
      
    },
    },
    fontFamily: {
      poppins: "Poppins",
      aubette: "Aubette",
      bandal: "Bandal",
      bricolage: "Bricolage",
    },
  },
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      {
        oceanic: {
          "color-scheme": "dark",
          primary: "#005f73",
          "primary-content": "#e0fbfc",
          secondary: "#0a9396",
          accent: "#94d2bd",
          neutral: "#293241",
          "base-100": "#1d3557",
          info: "#457b9d",
          success: "#2a9d8f",
          warning: "#f4a261",
          error: "#e76f51",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.5rem",
          "--tab-radius": "0.5rem",
        },
        sunsetGlow: {
          "color-scheme": "light",
          primary: "#ff6f61",
          "primary-content": "#1a202c",
          secondary: "#fbbf24",
          accent: "#f97316",
          neutral: "#2d3748",
          "base-100": "#ffffff",
          info: "#3b82f6",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--tab-radius": "0.25rem",
        },
        forestWhisper: {
          "color-scheme": "dark",
          primary: "#2a9d8f",
          "primary-content": "#f0efeb",
          secondary: "#264653",
          accent: "#e9c46a",
          neutral: "#2f3e46",
          "base-100": "#1b4332",
          info: "#a8dadc",
          success: "#8ecae6",
          warning: "#f4a261",
          error: "#e76f51",
          "--rounded-box": "1.5rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1rem",
          "--tab-radius": "1rem",
        },
        vintageVibes: {
          "color-scheme": "light",
          primary: "#b08968",
          "primary-content": "#1a202c",
          secondary: "#6d6875",
          accent: "#e5989b",
          neutral: "#4a4e69",
          "base-100": "#fff1e6",
          info: "#6d9dc5",
          success: "#4ecdc4",
          warning: "#ffb4a2",
          error: "#ff6f61",
          "--rounded-box": "0.4rem",
          "--rounded-btn": "0.4rem",
          "--rounded-badge": "0.4rem",
          "--tab-radius": "0.4rem",
        },
        midnightBlue: {
          "color-scheme": "dark",
          primary: "#1e3a8a",
          "primary-content": "#dbeafe",
          secondary: "#3b82f6",
          accent: "#6366f1",
          neutral: "#1e293b",
          "base-100": "#111827",
          info: "#60a5fa",
          success: "#4ade80",
          warning: "#facc15",
          error: "#f87171",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.5rem",
          "--tab-radius": "0.5rem",
        },
        solarFlare: {
          "color-scheme": "light",
          primary: "#ffb703",
          "primary-content": "#023047",
          secondary: "#fb8500",
          accent: "#ff6700",
          neutral: "#2d3142",
          "base-100": "#fdfdfd",
          info: "#219ebc",
          success: "#8ecae6",
          warning: "#ffb703",
          error: "#ef476f",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--tab-radius": "0.25rem",
        },
        mysticForest: {
          "color-scheme": "dark",
          primary: "#6b705c",
          "primary-content": "#fefae0",
          secondary: "#cb997e",
          accent: "#ddbea9",
          neutral: "#3d405b",
          "base-100": "#343a40",
          info: "#a5a58d",
          success: "#b7b7a4",
          warning: "#ffe8d6",
          error: "#d62828",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "0.75rem",
          "--tab-radius": "0.75rem",
        },
        neonDreams: {
          "color-scheme": "dark",
          primary: "#ff007f",
          "primary-content": "#0a0a0a",
          secondary: "#00c2ff",
          accent: "#00ff8c",
          neutral: "#202020",
          "base-100": "#121212",
          info: "#3a86ff",
          success: "#06d6a0",
          warning: "#ffd166",
          error: "#ef476f",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--tab-radius": "0.25rem",
        },
        desertMirage: {
          "color-scheme": "light",
          primary: "#e76f51",
          "primary-content": "#fff",
          secondary: "#f4a261",
          accent: "#e9c46a",
          neutral: "#2a9d8f",
          "base-100": "#fefae0",
          info: "#264653",
          success: "#2a9d8f",
          warning: "#e9c46a",
          error: "#e76f51",
          "--rounded-box": "1.2rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1rem",
          "--tab-radius": "1rem",
        },
        arcticChill: {
          "color-scheme": "light",
          primary: "#0077b6",
          "primary-content": "#ffffff",
          secondary: "#00b4d8",
          accent: "#90e0ef",
          neutral: "#023e8a",
          "base-100": "#caf0f8",
          info: "#0077b6",
          success: "#48cae4",
          warning: "#00b4d8",
          error: "#023e8a",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--tab-radius": "0.25rem",
        },
        urbanJungle: {
          "color-scheme": "dark",
          primary: "#4caf50",
          "primary-content": "#ffffff",
          secondary: "#ff9800",
          accent: "#9c27b0",
          neutral: "#212121",
          "base-100": "#263238",
          info: "#2196f3",
          success: "#4caf50",
          warning: "#ffc107",
          error: "#f44336",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.5rem",
          "--tab-radius": "0.5rem",
        },
        coralReef: {
          "color-scheme": "light",
          primary: "#ff6f61",
          "primary-content": "#1a202c",
          secondary: "#ffa600",
          accent: "#00a8cc",
          neutral: "#264653",
          "base-100": "#fefae0",
          info: "#006d77",
          success: "#83c5be",
          warning: "#e29578",
          error: "#ff6f61",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "0.75rem",
          "--tab-radius": "0.75rem",
        },
        royalElegance: {
          "color-scheme": "dark",
          primary: "#5a189a",
          "primary-content": "#ffffff",
          secondary: "#7b2cbf",
          accent: "#9d4edd",
          neutral: "#240046",
          "base-100": "#3c096c",
          info: "#4cc9f0",
          success: "#72efdd",
          warning: "#f7b801",
          error: "#ef233c",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--tab-radius": "0.25rem",
        },
      },
    ],
  },
  // eslint-disable-next-line no-undef
  plugins: [require("daisyui"),require('@tailwindcss/typography')],
};
