export type themes = string;

const themes: themes[] = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
    "oceanic",
    "sunsetGlow",
    "forestWhisper",
    "vintageVibes",
    "midnightBlue",
    "solarFlare",
    "mysticForest",
    "neonDreams",
    "desertMirage",
    "arcticChill",
    "urbanJungle",
    "coralReef",
    "royalElegance",
];

export default themes;
